name: base
dependencies:
- conda-forge::cudatoolkit=11.3.1
- numpy=1.21.2
- pillow=8.4.0
- pip=21.2.4
# - python=3.9.7
- pytorch::pytorch=1.10.2=py3.8_cuda11.3_cudnn8.2.0_0
- scipy=1.7.3
- pytorch::torchvision=0.11.3=py38_cu113
- ffmpeg=4.2.2
- tqdm=4.62.3
- pandas==1.3.0
# --------- pytorch --------- #

- conda-forge::pytorch-lightning>=1.5.0
- conda-forge::torchmetrics>=0.6.0

# --------- hydra --------- #
- conda-forge::hydra
# - conda-forge::hydra-core==1.1.0
# - conda-forge::hydra-colorlog==1.1.0
# - conda-forge::hydra-optuna-sweeper==1.1.0
# hydra-ax-sweeper
# hydra-ray-launcher
# hydra-submitit-launcher

# --------- loggers --------- #
- conda-forge::wandb
# neptune-client
# mlflow
# comet-ml
# torch_tb_profiler

# --------- linters --------- #
- conda-forge::pre-commit      # hooks for applying linters on commit
- conda-forge::black           # code formatting
- conda-forge::isort           # import sorting
- conda-forge::flake8          # code analysis

# --------- others --------- #
- conda-forge::python-dotenv   # loading env variables from .env file
- pytest          # tests
- conda-forge::sh              # for running bash commands in some tests
- conda-forge::rich            # beautiful text formatting in terminal
- conda-forge::termcolor==1.1.0
# - conda-forge::easy-to-hard-data==0.1.7
- conda-forge::icecream==2.1.0

# --------- lossland --------- #
- h5py
- seaborn

# --------- certification --------- #
- conda-forge::statsmodels
