_target_: src.models.LitModel

# name: FixedPointNet
init_std: 1.
arch:
  in_features: 2
  h_features: 4
  out_features: 2
  in_trans: linear
  f_solver: anderson
  f_thres: 30
  b_solver: anderson
  b_thres: 30
  stop_mode: rel
  num_layers: 5
  depth: 0
  width: 120
  core: mondeq
  block:
    norm_type: 'batch'
    activation: 'relu'
# Optim
lr: 0.001
lr_schedule:
  - 100
  - 200
  - 300
lr_decay: step
lr_factor: 0.5
optimizer_name: adam
warmup_period: 10
pretrain_steps: 3
compute_jac_loss: False
spectral_radius_mode: False
