# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml
  - model: fixedpoint.yaml
  - datamodule: dim2_rho2.yaml
  - callbacks: null
  - logger: null # set logger here or use command line (e.g. `python run.py logger=wandb`)

  - mode: default.yaml

  # optional local config
  - optional local: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  # sets output paths for all file logs to `logs/experiment/name'
  run:
    dir: logs/experiments/${name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/experiments/${name}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in pytorch, numpy and python.random
seed: null

checkpoint: ???
rect:
  - -1
  - -1
  - 1
  - 1
resolution:
  - 31
  - 31