_target_: src.models.LitModel

# name: FixedPointNet
init_std: 1.
arch:
  h_features:
    - 8
    - 16
  f_solver: anderson
  f_thres: 30
  f_eps: 0.001
  b_solver: anderson
  b_thres: 30
  b_eps: 0.001
  stop_mode: rel
  num_layers: 5
  depth: 0
  core: deq
# Optim
lr: 0.001
lr_schedule:
  - 100
  - 200
  - 300
lr_decay: step
lr_factor: 0.5
optimizer_name: adam
warmup_period: 10
pretrain_steps: 3
compute_jac_loss: False
spectral_radius_mode: False
