_target_: src.models.LitModel

# name: FixedPointNet
init_std: 1.
arch:
  core: recur
  h_features:
    - 8
    - 16
  num_layers: 1
  depth: 0
# Optim
lr: 5e-4
lr_schedule:
  - 120
  - 280
lr_decay: step
lr_factor: 0.2
optimizer_name: adam
compute_jac_loss: False
spectral_radius_mode: False
noise_sd: 0.0